# Generated by Selenium IDE
import pytest
import time
import json
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys
from selenium.common.exceptions import TimeoutException, ElementClickInterceptedException, NoSuchElementException


@pytest.mark.xfail(reason="PHPTravels return_time alani, gercek kullanici tiklamasinda calisiyor ama Selenium WebDriver ile (dogru elemana tiklansa bile) saat paneli acilmiyor - sitenin otomasyon tespiti/engellemesi oldugu dusunuluyor.")
#beklenen başarısızlıktan dolayı XFAIL olarak işaretlendi. 
# Bu test, PHPTravels sitesindeki return_time alanının Selenium WebDriver ile doğru şekilde çalışmadığını doğrulamak için tasarlanmıştır. 
# Gerçek kullanıcı etkileşiminde çalışmasına rağmen, otomasyon tespiti nedeniyle saat paneli açılmamaktadır.
class TestAracAramaTesti3():
  def setup_method(self, method):
    self.driver = webdriver.Firefox()
    self.vars = {}
    self.wait = WebDriverWait(self.driver, 10)

  def teardown_method(self, method):
    self.driver.quit()

  def click_when_ready(self, by, selector):
    element = self.wait.until(expected_conditions.element_to_be_clickable((by, selector)))
    time.sleep(0.5)
    try:
        element.click()
    except ElementClickInterceptedException:
        # Uzerinde bir overlay/backdrop kalmis olabilir -> ESC ile kapatmayi dene
        ActionChains(self.driver).send_keys(Keys.ESCAPE).perform()
        time.sleep(0.3)
        element = self.wait.until(expected_conditions.element_to_be_clickable((by, selector)))
        try:
            element.click()
        except ElementClickInterceptedException:
            # Son care: JS ile dogrudan tikla (overlay kontrolunu atlar)
            self.driver.execute_script("arguments[0].click();", element)

  def click_nth_visible_day(self, n):
    elements = self.driver.find_elements(
        By.XPATH,
        "//div[contains(@class, 'day') and not(contains(@class, 'disabled'))]"
    )
    visible_days = [el for el in elements if el.is_displayed()]
    time.sleep(0.3)
    visible_days[n].click()

  def click_nth_visible(self, css_class_contains, n=0):
    # click_nth_visible_day ile ayni mantik, genel amacli:
    # belirli bir data-* degerini tahmin etmek yerine, o class'a sahip devre disi olmayan ve ekranda GORUNEN n. elemani bulup tiklar.
    # devre disi olmayan ve ekranda GORUNEN n. elemani bulup tiklar.
    elements = self.driver.find_elements(
        By.XPATH,
        f"//div[contains(@class, '{css_class_contains}')]"
    )
    visible = [el for el in elements if el.is_displayed()]
    time.sleep(0.3)
    visible[n].click()

  def test_aracAramaTesti3(self):
    # 1 | open
    self.driver.get("https://phptravels.net/")
    # 2 | setWindowSize
    self.driver.set_window_size(1550, 830)

    # Demo uyari penceresi CIKARSA kapat
    try:
        self.wait.until(expected_conditions.presence_of_element_located(
            (By.XPATH, "//button[contains(text(), 'I Understand')]")))
        self.driver.find_element(By.XPATH, "//button[contains(text(), 'I Understand')]").click()
    except TimeoutException:
        pass

    # 3 | Cars sekmesine gec
    self.click_when_ready(By.XPATH, "//button[@role='tab']//span[contains(text(), 'Cars')]")
    # 4 | pick-up kutusuna tikla
    self.click_when_ready(By.ID, "car_pick_t")
    # 5 | "charles" yaz
    self.driver.find_element(By.ID, "car_pick_q").send_keys("charles")
    # 6 | onerilen listeden sec
    self.click_when_ready(By.CSS_SELECTOR, ".gap-3:nth-child(3) > .text-sm")
    # 7 | return kutusuna tikla
    self.click_when_ready(By.CSS_SELECTOR, "#car_drop_t .text-\\[\\#98a2b3\\]")
    # 8 | "marse" yaz
    self.driver.find_element(By.ID, "car_drop_q").send_keys("marse")
    # 9 | onerilen listeden sec
    self.click_when_ready(By.CSS_SELECTOR, ".gap-3:nth-child(2) > .text-sm")

    time.sleep(0.5)

    # 10 | pickup_date'e tikla
    self.click_when_ready(By.NAME, "pickup_date")

    # 11 | takvimden ilk GORUNUR tiklanabilir gunu sec (gidis tarihi)
    time.sleep(1)
    self.click_nth_visible_day(0)

    # 12 | takvimden ikinci GORUNUR tiklanabilir gunu sec (donus tarihi)
    time.sleep(0.5)
    self.click_nth_visible_day(1)

    # 13 | takvim overlay'ini kapat ve return_time'a tikla
    time.sleep(0.5)
    try:
        overlay = self.driver.find_element(By.CSS_SELECTOR, ".datepicker-overlay")
        if overlay.is_displayed():
            # Overlay kendi kapanma davranisini tetiklemek icin dogrudan
            # overlay'e (arka plana) tikla -> ESC bu overlay'i kapatmiyor
            overlay.click()
            self.wait.until(expected_conditions.invisibility_of_element_located(
                (By.CSS_SELECTOR, ".datepicker-overlay")))
    except NoSuchElementException:
        pass
    except TimeoutException:
        # Overlay hala kapanmadiysa son care JS ile DOM'dan gizlemeyi dene
        self.driver.execute_script(
            "document.querySelectorAll('.datepicker-overlay').forEach(e => e.style.display='none');"
        )
        time.sleep(0.3)


     # 14 | return_time'a tikla -> DIKKAT: input'un KENDISINE degil, onu saran
    # ve gercekte @click ile input'a focus() veren "field-box-segment" div'ine
    # tikliyoruz (DevTools'ta bulunan gercek tiklanabilir alan burasi).
    self.click_when_ready(
        By.XPATH,
        "//input[@name='return_time']/ancestor::div[contains(@class, 'field-box-segment')][1]"
    )
 
    # 15 | saat sec -> 'presence' degil 'visibility' bekliyoruz, cunku bu
    # elemanlar panel kapaliyken de DOM'da var oluyor, sadece gizli oluyorlar.
    self.wait.until(expected_conditions.visibility_of_element_located(
        (By.CSS_SELECTOR, ".tp-hour")))
    self.click_when_ready(By.CSS_SELECTOR, ".tp-hour[data-hour='16']")


     # 16 | dakika sec
    self.wait.until(expected_conditions.visibility_of_element_located(
        (By.CSS_SELECTOR, ".tp-minute")))
    self.click_when_ready(By.CSS_SELECTOR, ".tp-minute[data-minute='30']")
 
    # 17 | ara butonuna tikla
    time.sleep(1)
    self.click_when_ready(By.CSS_SELECTOR, ".col-span-1:nth-child(5) > .btn")