# Generated by Selenium IDE
import pytest
import time
import json
from selenium import webdriver
from selenium.webdriver.common.by import By
#nasıl bulacağımızı belirtmek için by kütüphanesini kullanırız. Örneğin, By.ID, By.NAME, By.CSS_SELECTOR gibi.
from selenium.webdriver.common.action_chains import ActionChains



from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities

class TestAracAramaTesti2():
  def setup_method(self, method):
    self.driver = webdriver.Firefox()
    self.driver.get("https://phptravels.net")
    self.vars = {}
#her test başlamadan önce çalışacak olan setup_method fonksiyonu, Firefox tarayıcısını başlatır ve vars adında bir sözlük oluşturur. Bu sözlük, test sırasında kullanılacak değişkenleri saklamak için kullanılabilir.
  


  def teardown_method(self, method):
    self.driver.quit()
#teardown_method fonksiyonu, her test tamamlandıktan sonra çalışır ve tarayıcıyı kapatır. Bu, testlerin birbirinden bağımsız olarak çalışmasını sağlar ve kaynakların serbest bırakılmasını garanti eder.
  
  def test_aracAramaTesti2(self):
    # Test name: Arac_Arama_Testi2
    # Step # | name | target | value

   wait=WebDriverWait(self.driver, 10)

# önce demo uyarı penceresini bekle ve kapat
   wait.until(expected_conditions.presence_of_element_located(
        (By.XPATH, "//button[contains(text(), 'I Understand')]")))
   self.driver.find_element(By.XPATH, "//button[contains(text(), 'I Understand')]").click()


   wait.until(expected_conditions.presence_of_element_located(
        (By.XPATH, "//button[@role='tab']//span[contains(text(), 'Cars')]")))
   self.driver.find_element(By.XPATH, "//button[@role='tab']//span[contains(text(), 'Cars')]").click()

# şimdi ana arama kutusunun gelmesini bekle
   wait.until(expected_conditions.presence_of_element_located((By.ID, "car_pick_t")))



    # 1 | click | id=car_pick_t | 
   self.driver.find_element(By.ID, "car_pick_t").click()
#find_element(By.ID, "car_pick_t").click() ifadesi, sayfadaki "car_pick_t" ID'sine sahip öğeyi bulur ve üzerine tıklar. Bu, genellikle bir açılır menüyü veya bir giriş alanını etkinleştirmek için kullanılır.

    # 2 | type | id=car_pick_q | charles
   self.driver.find_element(By.ID, "car_pick_q").send_keys("charles")
#send_keys("charles") ifadesi, "car_pick_q" ID'sine sahip giriş alanına "charles" metnini yazar. Bu, kullanıcı girişini simüle etmek için kullanılır.

    # 3 | click | css=.gap-3:nth-child(3) > .text-sm | 
   self.driver.find_element(By.CSS_SELECTOR, ".gap-3:nth-child(3) > .text-sm").click()
#css=.gap-3:nth-child(3) > .text-sm ifadesi, CSS seçici kullanarak belirli bir öğeyi bulur ve üzerine tıklar. Bu, genellikle bir liste öğesini veya bir düğmeyi seçmek için kullanılır.

    # 4 | click | css=#car_drop_t .text-\[11px\] | 
   self.driver.find_element(By.CSS_SELECTOR, "#car_drop_t .text-\\[11px\\]").click()
#car_drop_t .text-\[11px\] ifadesi, CSS seçici kullanarak "car_drop_t" ID'sine sahip öğe içindeki belirli bir metin boyutuna sahip öğeyi bulur ve üzerine tıklar. Bu, genellikle bir açılır menüyü veya bir giriş alanını etkinleştirmek için kullanılır.

    # 5 | type | id=car_drop_q | marse
   self.driver.find_element(By.ID, "car_drop_q").send_keys("marse")
#car drop_q ID'sine sahip giriş alanına "marse" metnini yazar. Bu, kullanıcı girişini simüle etmek için kullanılır.

    # 6 | click | css=.gap-3:nth-child(2) > .text-sm | 
   self.driver.find_element(By.CSS_SELECTOR, ".gap-3:nth-child(2) > .text-sm").click()
#css=.gap-3:nth-child(2) > .text-sm ifadesi, CSS seçici kullanarak belirli bir öğeyi bulur ve üzerine tıklar. Bu, genellikle bir liste öğesini veya bir düğmeyi seçmek için kullanılır.

    # 7 | click | name=pickup_date | 
   self.driver.find_element(By.NAME, "pickup_date").click()
#name=pickup_date ifadesi, name özniteliğine sahip öğeyi bulur ve üzerine tıklar. Bu, genellikle bir tarih seçici veya bir giriş alanını etkinleştirmek için kullanılır.

    # 8 | click | css=.datepicker:nth-child(14) tr:nth-child(4) > .p-0\.2:nth-child(4) > .day | 
   self.driver.find_element(By.CSS_SELECTOR, ".datepicker:nth-child(14) tr:nth-child(4) > .p-0\\.2:nth-child(4) > .day").click()
#css=.datepicker:nth-child(14) tr:nth-child(4) > .p-0\.2:nth-child(4) > .day ifadesi, CSS seçici kullanarak belirli bir tarih öğesini bulur ve üzerine tıklar. Bu, genellikle bir tarih seçici içindeki belirli bir günü seçmek için kullanılır.

    # 9 | click | css=.datepicker:nth-child(15) tr:nth-child(5) > .p-0\.2:nth-child(1) > .day | 
   self.driver.find_element(By.CSS_SELECTOR, ".datepicker:nth-child(15) tr:nth-child(5) > .p-0\\.2:nth-child(1) > .day").click()
#css=.datepicker:nth-child(15) tr:nth-child(5) > .p-0\.2:nth-child(1) > .day ifadesi, CSS seçici kullanarak belirli bir tarih öğesini bulur ve üzerine tıklar. Bu, genellikle bir tarih seçici içindeki belirli bir günü seçmek için kullanılır.

    # 10 | click | css=.col-span-1 > .btn | 
   self.driver.find_element(By.CSS_SELECTOR, ".col-span-1 > .btn").click()
#col-span-1 > .btn ifadesi, CSS seçici kullanarak belirli bir düğmeyi bulur ve üzerine tıklar. Bu, genellikle bir formu göndermek veya bir işlemi başlatmak için kullanılır.

    # 11 | mouseOver | css=.p-0 | 
   element = self.driver.find_element(By.CSS_SELECTOR, ".p-0")
   actions = ActionChains(self.driver)
   actions.move_to_element(element).perform()
  
