server{
    listen 80;
    location / {
        proxy_pass http://admin-panel:8000;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
    }
}
server{
    listen 85;
    location / {
        proxy_pass http://user-panel:8000;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
    }
}